config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"
  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
  end
  resources :books, only:[:index, :show, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, length: { maximum: 200 },  presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, length: {maximum: 400}, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follows, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    follows << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def follows?(other_user)
    follows.include?(other_user)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to request.referer
  end

  private
    def book_comment_params
      params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only:[:edit, :update]

  def index
    @new_book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @books = Book.all
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      redirect_to book_path(@new_book), notice: "You have created book successfully"
    else
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully"
    else
      render :edit
    end

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to request.referer
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to request.referer
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only:[:edit, :update]

  def index
    @users = User.all
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully"
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.follows
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>
<%= render 'layouts/errors', obj: book %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <%= f.label :opinion, "Opinion" %>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
        <% if book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(book), method: :delete, class: "favorite-color" do %>
              ♥<%= book.favorites.count %>
            <% end %>
          </td>
        <% else %>
          <td >
            <%= link_to book_favorites_path(book), method: :post do %>
              ♥<%= book.favorites.count %>
            <% end %>
          </td>
        <% end %>
        <td>
          コメント件数：<%= book.book_comments.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render "form", book: @book %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info" ,user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
      <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "index", books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %><br />
                  <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <% if @book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(@book), method: :delete, class: "favorite-color" do %>
                  ♥<%= @book.favorites.count %>
                <% end %>
              </td>
            <% else %>
              <td>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  ♥<%= @book.favorites.count %>
                <% end %>
              </td>
            <% end %>
            <td>
              コメント件数：<%= @book.book_comments.count %>
            </td>
            <% if current_user == @book.user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
              </td>
            <% end %>

          </tr>
        </tbody>
      </table>
      <div class="comments">
        <% @book.book_comments.each do |book_comment| %>
          <%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
          <%= book_comment.user.name %>
          <% if current_user == book_comment.user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
          <% end %>
          <p>
            <%= link_to book_comment.comment, book_path(@book) %>
          </p>
        <% end %>
      </div>
      <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <div class="comment-form">
            <%= f.text_area :comment, rows:'5' %>
          </div>
          <div>
            <%= f.submit "送信" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>  !!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<h2><%= params[:range] %>s search for "<%= params[:word] %>"</h2>
<table class="table">
  <% if @range == "User" %>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
        </td>
        <td>
          <%= user.name %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <% else %>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book.id) %>
          </td>
          <td>
            <%= book.body %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/_follow.html.erb
<% if users.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          フォロー数：<%= user.follows.count %>
        </td>
        <td>
          フォロワー数：<%= user.follows.count %>
        </td>
        <td>
          <%= link_to "Show", user_path(user) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          フォロー数：<%= user.follows.count %>
        </td>
        <td>
          フォロワー数：<%= user.follows.count %>
        </td>
        <td>
          <% if current_user != user %>
            <% if current_user.follows?(user) %>
              <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),
                          html: { method: :delete }, local: true) do |f| %>
                <%= f.submit "フォロー外す", class: "btn btn-link" %>
              <% end %>
            <% else %>
              <%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
                <div><%= hidden_field_tag :followed_id, user.id %></div>
                <%= f.submit "フォローする", class: "btn btn-link" %>
              <% end %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to "Show", user_path(user.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class="table">
  <tbody>
    <tr>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.follows.count, follows_user_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, followers_user_path(user) %></th>
    </tr>
  </tbody>
</table>

<% if current_user == user %>
  <div class="row">
    <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>
<% else %>
  <% if current_user.follows?(user) %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),
                html: { method: :delete }, local: true) do |f| %>
      <%= f.submit "フォロー外す", class: "btn btn-info" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
      <div><%= hidden_field_tag :followed_id, user.id %></div>
      <%= f.submit "フォローする", class: "btn btn-success" %>
    <% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user, local: true do |f| %>
      <%= render "layouts/errors", obj: @user %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :image, "Image" %>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "Introduction" %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<%= render "follow", users: @users %>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<%= render "follow", users: @users %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>